data1<-read.table("E:\\test\\文献分享\\转正汇报\\neg-quant.txt",header=T,sep="\t")
up_data<-subset(data1,ratio>=1.2&t.test_p.value_BHcorrect<=0.05&VIP>=1)
down_data<-subset(data1,ratio<=0.833&t.test_p.value_BHcorrect<=0.05&VIP>=1)
total_data<-subset(data1,(ratio>=1.2|ratio<=0.833)&t.test_p.value_BHcorrect<=0.05&VIP>=1)

up<-table(up_data$sample)
down<-table(down_data$sample)
total<-table(total_data$sample)
sum_data<-cbind(up,down,total)
sum_data1<-as.data.frame(sum_data)
a<-as.data.frame(matrix(c("1:2","1:3","2:3"),3,1))
b<-cbind(a,sum_data1)
colnames(b)<-c("group","up","down","total")
write.table(b,out_file,row.names = F,sep="\t")